# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build-and-Release

on:
  push:

jobs:
  build_assets_alpine_arm:
    name: Build assets - Alpine and ARM
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - distro: "python:3.11-alpine3.18"
            arch: arm64
            distro_name: alpine
          - distro: "python:3.11-alpine3.18"
            arch: x86_64
            distro_name: alpine
          - distro: "python:3.11"
            arch: arm64
            distro_name: linux
            
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: ${{ matrix.arch }}
    - name: Run in Docker
      run: |
        docker run \
          -t \
          --rm \
          -v $(pwd):/${{ github.workspace }} \
          -w ${{ github.workspace }} \
          --platform linux/${{ matrix.arch }} \
          ${{ matrix.distro }} \
          ./scripts/build_${{ matrix.distro_name }}_arm.sh ${{ matrix.distro_name }}_${{ matrix.arch }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      if: inputs.release == false
      with:
        path: ./dist/codecovcli_${{ matrix.distro_name }}_${{ matrix.arch }}
