# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build-and-Release

on:
  push:

jobs:

  buildassets:
    name: Build packages
    runs-on: 
    strategy:
      fail-fast: true
      matrix:
        include:
          - arch: linux/arm64
          - arch: linux/x86_64
    container:
      image: python:3.11-alpine3.18
      options: --platform ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install dependencies
      run: |
        ls
        uname -a

